name: Latest blog post workflow
on:
  schedule:
    - cron: "0 0 * * 0" # Runs every week
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://odhyp.com/index.xml"
          template: "$newline - [$title]($url) ($date)"
          date_format: "mmm d, yyyy"
          commit_message: "chore: update recent posts"
          committer_username: "github-actions[bot]"
          committer_email: "41898282+github-actions[bot]@users.noreply.github.com"
