name: Update Recent Blog Posts and WakaTime Stats

on:
  workflow_dispatch: # Allow manual trigger
  schedule:
    - cron: "0 20 * * *" # Runs at 20:00 UTC (3:00 AM Jakarta time)

jobs:
  update-recent-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Recent Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://odhyp.com/index.xml"
          # Content
          template: "$newline- [$title]($url) ($date)"
          date_format: "mmm d, yyyy"
          # Commit
          commit_message: "chore: update recent posts"
          committer_username: GitHub Actions[Bot]
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com

  update-waka-time:
    runs-on: ubuntu-latest
    needs: update-recent-blog # Ensure this job runs after blog update job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update WakaTime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Content
          CODE_LANG: bash
          LANG_COUNT: 4
          SHOW_TIME: true
          SHOW_TOTAL: true
          STOP_AT_OTHER: false
          IGNORED_LANGUAGES: YAML JSON TOML SVG TXT
          # Commit
          COMMIT_MESSAGE: "chore: update WakaTime stats"
          TARGET_BRANCH: main
          TARGET_PATH: README.md
          COMMITTER_NAME: GitHub Actions[Bot]
          COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
