name: Update WakaTime Stats

on:
  workflow_dispatch: # Allow manual trigger
  schedule:
    - cron: "0 0 * * *" # Runs at 7:00 AM WIB daily

jobs:
  update-waka-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update WakaTime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Content
          CODE_LANG: bash
          TIME_RANGE: all_time
          LANG_COUNT: 5
          SHOW_TIME: true
          SHOW_TOTAL: true
          STOP_AT_OTHER: false
          IGNORED_LANGUAGES: YAML JSON TOML SVG TXT
          # Commit
          COMMIT_MESSAGE: "chore: update WakaTime stats"
          TARGET_BRANCH: main
          TARGET_PATH: README.md
          COMMITTER_NAME: GitHub Actions[Bot]
          COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
